/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String _kFontPkg = null;

  static const IconData trending_down = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trending_up = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glass = IconData(0xe8ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music = IconData(0xe8ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe8ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_circled = IconData(0xe8af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe8b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_circled = IconData(0xe8b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_1 = IconData(0xe8b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_circled = IconData(0xe8b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_empty = IconData(0xe8b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_1 = IconData(0xe8b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_circled = IconData(0xe8b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_empty_1 = IconData(0xe8b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_1 = IconData(0xe8b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe8b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_circled = IconData(0xe8ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData torso = IconData(0xe8bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe8bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_circled = IconData(0xe8bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_alt = IconData(0xe8be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videocam = IconData(0xe8bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_chat = IconData(0xe8c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture_1 = IconData(0xe8c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_1 = IconData(0xe8c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo = IconData(0xe8c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo_circled = IconData(0xe8c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_large = IconData(0xe8c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th = IconData(0xe8c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_list = IconData(0xe8c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData view_mode = IconData(0xe8c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok = IconData(0xe8c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_circled = IconData(0xe8ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_circled2 = IconData(0xe8cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe8cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circled = IconData(0xe8cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circled2 = IconData(0xe8ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe8cf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_circled = IconData(0xe8d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe8d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_circled = IconData(0xe8d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe8d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_circled = IconData(0xe8d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circled = IconData(0xe8d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_1 = IconData(0xe8d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_circled = IconData(0xe8d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData website = IconData(0xe8d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData website_circled = IconData(0xe8d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach = IconData(0xe8da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach_circled = IconData(0xe8db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_1 = IconData(0xe8dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_circled = IconData(0xe8dd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open = IconData(0xe8de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open_alt = IconData(0xe8df, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_1 = IconData(0xe8e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_off = IconData(0xe8e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag_1 = IconData(0xe8e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tags = IconData(0xe8e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_1 = IconData(0xe8e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_empty = IconData(0xe8e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag_1 = IconData(0xe8e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag_circled = IconData(0xe8e7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up_1 = IconData(0xe8e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_down_1 = IconData(0xe8e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_1 = IconData(0xe8ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_alt = IconData(0xe8eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload_1 = IconData(0xe8ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe8ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quote = IconData(0xe8ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quote_circled = IconData(0xe8ef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export_icon = IconData(0xe8f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_1 = IconData(0xe8f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_circled = IconData(0xe8f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe8f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_circled = IconData(0xe8f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_alt = IconData(0xe8f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData print = IconData(0xe8f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData retweet = IconData(0xe8f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe8f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_alt = IconData(0xe8f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe8fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning_1 = IconData(0xe8fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamation = IconData(0xe8fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error = IconData(0xe8fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error_alt = IconData(0xe8fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_1 = IconData(0xe8ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_circled = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass_circled = IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_1 = IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_circled = IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc = IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_circled = IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_new = IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_new_circled = IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_circled = IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_close = IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_open = IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rss = IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_1 = IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_circled = IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog_1 = IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog_circled = IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cogs = IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wrench = IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wrench_circled = IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basket = IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basket_circled = IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_circled = IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_1 = IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_circled = IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_off = IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_down = IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_1 = IconData(0xe91d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_up = IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData headphones = IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_1 = IconData(0xe920, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_circled = IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightbulb = IconData(0xe922, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightbulb_alt = IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block = IconData(0xe924, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_full = IconData(0xe925, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_full_alt = IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_small = IconData(0xe927, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_vertical = IconData(0xe928, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_horizontal = IconData(0xe929, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move_1 = IconData(0xe92a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_in = IconData(0xe92b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_out = IconData(0xe92c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_open = IconData(0xe92d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_open = IconData(0xe92e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_open = IconData(0xe92f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_open = IconData(0xe930, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down = IconData(0xe931, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left = IconData(0xe932, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right = IconData(0xe933, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up = IconData(0xe934, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_circled = IconData(0xe935, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_circled = IconData(0xe936, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_circled = IconData(0xe937, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_circled = IconData(0xe938, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_hand = IconData(0xe939, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_hand = IconData(0xe93a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_hand = IconData(0xe93b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_hand = IconData(0xe93c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cw = IconData(0xe93d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cw_circled = IconData(0xe93e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrows_cw = IconData(0xe93f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shuffle = IconData(0xe940, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe941, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_circled = IconData(0xe942, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_circled2 = IconData(0xe943, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop = IconData(0xe944, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop_circled = IconData(0xe945, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause_circled = IconData(0xe947, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData record = IconData(0xe948, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eject = IconData(0xe949, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backward = IconData(0xe94a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backward_circled = IconData(0xe94b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_backward = IconData(0xe94c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_forward = IconData(0xe94d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward = IconData(0xe94e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward_circled = IconData(0xe94f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData step_backward = IconData(0xe950, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData step_forward = IconData(0xe951, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData target = IconData(0xe952, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal = IconData(0xe953, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop = IconData(0xe954, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop_circled = IconData(0xe955, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop_1 = IconData(0xe956, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop_circled = IconData(0xe957, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData network = IconData(0xe958, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox_1 = IconData(0xe959, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox_circled = IconData(0xe95a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox_alt = IconData(0xe95b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe = IconData(0xe95c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_alt = IconData(0xe95d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_1 = IconData(0xe95e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_circled = IconData(0xe95f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flight = IconData(0xe960, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leaf_1 = IconData(0xe961, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font = IconData(0xe962, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fontsize = IconData(0xe963, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bold_1 = IconData(0xe964, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData italic_1 = IconData(0xe965, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_height = IconData(0xe966, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_width = IconData(0xe967, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_left = IconData(0xe968, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_center = IconData(0xe969, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_right = IconData(0xe96a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_justify = IconData(0xe96b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_1 = IconData(0xe96c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData indent_left = IconData(0xe96d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData indent_right = IconData(0xe96e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase_1 = IconData(0xe96f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData off = IconData(0xe970, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData road = IconData(0xe971, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qrcode = IconData(0xe972, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode = IconData(0xe973, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData braille = IconData(0xe974, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_1 = IconData(0xe975, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adjust = IconData(0xe976, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tint = IconData(0xe977, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe978, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_empty = IconData(0xe979, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData asterisk = IconData(0xe97a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift_1 = IconData(0xe97b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire = IconData(0xe97c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnet = IconData(0xe97d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart = IconData(0xe97e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_circled = IconData(0xe97f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card = IconData(0xe980, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData megaphone = IconData(0xe981, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard = IconData(0xe982, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hdd = IconData(0xe983, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = IconData(0xe984, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData certificate = IconData(0xe985, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tasks = IconData(0xe986, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe987, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gauge = IconData(0xe988, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smiley = IconData(0xe989, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smiley_circled = IconData(0xe98a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData address_book = IconData(0xe98b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData address_book_alt = IconData(0xe98c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData asl = IconData(0xe98d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glasses = IconData(0xe98e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hearing_impaired = IconData(0xe98f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iphone_home = IconData(0xe990, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe991, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adult = IconData(0xe992, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData child = IconData(0xe993, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blind = IconData(0xe994, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guidedog = IconData(0xe995, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accessibility = IconData(0xe996, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData universal_access = IconData(0xe997, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male = IconData(0xe998, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female = IconData(0xe999, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData behance = IconData(0xe99a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blogger = IconData(0xe99b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc = IconData(0xe99c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData css = IconData(0xe99d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delicious = IconData(0xe99e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deviantart = IconData(0xe99f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData digg = IconData(0xe9a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dribbble = IconData(0xe9a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe9a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flickr = IconData(0xe9a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData foursquare = IconData(0xe9a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData friendfeed = IconData(0xe9a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData friendfeed_rect = IconData(0xe9a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xe9a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_text = IconData(0xe9a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googleplus = IconData(0xe9a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe9aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xe9ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData path = IconData(0xe9ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picasa = IconData(0xe9ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pinterest = IconData(0xe9ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reddit = IconData(0xe9af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skype = IconData(0xe9b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slideshare = IconData(0xe9b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stackoverflow = IconData(0xe9b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stumbleupon = IconData(0xe9b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xe9b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tumblr = IconData(0xe9b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vimeo = IconData(0xe9b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vkontakte = IconData(0xe9b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData w3c = IconData(0xe9b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wordpress = IconData(0xe9b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube = IconData(0xe9ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pulse = IconData(0xf31f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
